apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      imagePullSecrets:
        - name: application-collection
      containers:
      - name: redis
        image: dp.apps.rancher.io/containers/redis:7.2.16-24.12
        ports:
        - containerPort: 6379
